apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: invoices-api
  annotations:
    konghq.com/strip-path: "true"
    konghq.com/plugins: httpbin-auth
    kubernetes.io/ingress.class: kong
spec:
  rules:
  - http:
      paths:
      - path: /invoices
        backend:
          serviceName: epoic-invoices
          servicePort: 8081