# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmaps-userdata-ai
data:
  couchbase.server.hostname: userdata-couchbasedb
  couchbase.server.bucketname_userdata: userdata
