apiVersion: v1
kind: ConfigMap
metadata:
  name: postgrescustomer-init-config
data:
  #init-sql: "CREATE TABLE public.motivationalprofiling(userid text NOT NULL,homeui text,homeuisetdate text NOT NULL,motivationalprofilingjson json,CONSTRAINT motivationalprofiling_pkey PRIMARY KEY (userid))"
  init-sql: "CREATE TABLE customers (customer_id BIGINT GENERATED ALWAYS AS IDENTITY,first_name VARCHAR(100),last_name VARCHAR(100),phone VARCHAR(50),email VARCHAR(50),PRIMARY KEY(customer_id)); CREATE TABLE addresses (customer_id BIGINT,address_id BIGINT GENERATED ALWAYS AS IDENTITY,type VARCHAR(100),address VARCHAR(100),city VARCHAR(50),postal_code VARCHAR(50),state VARCHAR(50),country VARCHAR(50),fk_cust_id BIGINT,PRIMARY KEY(address_id),FOREIGN KEY(fk_cust_id)REFERENCES customers(customer_id)ON DELETE CASCADE);"
