# What do we want / asking for it
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-customer-pvc
spec:
  storageClassName: postgresstoragecustomer
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
#How to we want it implemeneted, what pyschical storage 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-local-storage-customer
spec:
  storageClassName: postgresstoragecustomer
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce 
  hostPath:
    path: /mnt/postgres/customer
    type: DirectoryOrCreate

