# What do we want / asking for it
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-invoices-pvc
spec:
  storageClassName: postgresstorageinvoices
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
#How to we want it implemeneted, what pyschical storage 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-local-storage-invoices
spec:
  storageClassName: postgresstorageinvoices
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce 
  hostPath:
    path: /mnt/postgres/invoices
    type: DirectoryOrCreate

