# What do we want / asking for it
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-orders-pvc
spec:
  storageClassName: cloud-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi


