apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresproducts-init-config
data:
  #init-sql: "CREATE TABLE public.motivationalprofiling(userid text NOT NULL,homeui text,homeuisetdate text NOT NULL,motivationalprofilingjson json,CONSTRAINT motivationalprofiling_pkey PRIMARY KEY (userid))"
  init-sql: "CREATE TABLE products (product_id BIGINT GENERATED ALWAYS AS IDENTITY,product_name VARCHAR(100),product_type VARCHAR(50),product_description VARCHAR(300),product_price NUMERIC(8, 2),product_currency VARCHAR(3),product_image BYTEA,user_d VARCHAR(50),created_date VARCHAR(50),modified_date VARCHAR(50),active BOOLEAN,PRIMARY KEY(product_id));"
